# Generated by Django 4.2.26 on 2025-11-20 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("price", models.DecimalField(decimal_places=0, max_digits=5)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("starter", "Starter"),
                            ("main", "Main Course"),
                            ("dessert", "Dessert"),
                        ],
                        max_length=20,
                    ),
                ),
                ("vegetarian", models.BooleanField(default=False)),
                ("gluten_free", models.BooleanField(default=False)),
            ],
        ),
    ]
